name: Build and Push Image

on:
  workflow_call:
    inputs:
      tag:        { required: true, type: string }
      latest_tag: { required: true, type: string }

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Owner will be computed inline (lowercased) when building tags

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_KEY }}

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & push (linux/amd64)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ toLower(github.repository_owner) }}/laravel-demo:${{ inputs.tag }}
            ghcr.io/${{ toLower(github.repository_owner) }}/laravel-demo:${{ inputs.latest_tag }}
          # tags: |
          #   ghcr.io/${{ steps.vars.outputs.OWNER_LC }}/${{ steps.vars.outputs.IMAGE_NAME }}:${{ inputs.tag }}
          #   ghcr.io/${{ steps.vars.outputs.OWNER_LC }}/${{ steps.vars.outputs.IMAGE_NAME }}:${{ inputs.latest_tag }}
          # cache-from: type=gha
          cache-to: type=gha,mode=max

